MONGODB_HOST: mongodb-{{ env }}.daws86sd.fun # mongodb-dev.daws86sd.fun
REDIS_HOST: redis-{{ env }}.daws86sd.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.daws86sd.fun
CART_HOST: cart.backend-alb-{{ env }}.daws86sd.fun
USER_HOST: user.backend-alb-{{ env }}.daws86sd.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.daws86sd.fun
MYSQL_HOST: mysql-{{ env }}.daws86sd.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.daws86s.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.daws86sd.fun